---
  - name: installing_elasticsearch
    hosts: elastic
    become: yes
    tasks:
      - name: sudo apt-get update
        apt: 
          update_cache: yes
      - name: installing jvm
        apt: 
          name: openjdk-11-jdk-headless
      - name: exporting environment variables
        shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64          
      - name: Get the keys before installing elastic-search
        shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add - 
      - name: install apt-transport-https
        apt: 
          name: apt-transport-https
      - name: creating repository for elastic-search
        shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list                   
      - name: update and install elastic-search
        apt:
          update_cache: yes
          name: elasticsearch
          state: latest          
