[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
[certificatesResolvers.lets-encrypt.acme]
  email = "cahaynk.intern@phonepe.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "web"

[providers.file]
  filename = "traefik_secure.toml"

[pilot]
  token = "ced3126f-f9c5-45e4-ad18-d516082890eb"
[providers.marathon]
  endpoint = "http://192.168.1.17:8080"
  exposedByDefault = true
  watch = true
  respectReadinessChecks = true
