[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$2AZ0HvFK$RHhCE103dquO6RkKRD2pk0"
  ]

[http.routers.api]
  rule = "Host(`192.168.1.30`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
